# Generated by Django 3.1.2 on 2020-10-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=300)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.CharField(max_length=400)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('thumbnail_image', models.FileField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
