# Generated by Django 3.1.2 on 2020-10-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=10000)),
                ('video_title', models.CharField(max_length=400)),
                ('video_subtitle', models.CharField(max_length=400)),
            ],
        ),
    ]
